#ifndef PROTO_ALL_H
#define PROTO_ALL_H

#include <proto/alib.h>
#include <proto/amigaguide.h>
#include <proto/arexx.h>
#include <proto/asl.h>
#include <proto/battclock.h>
#include <proto/battmem.h>
#include <proto/bevel.h>
#include <proto/bitmap.h>
#include <proto/bullet.h>
#include <proto/button.h>
#include <proto/cardres.h>
#include <proto/checkbox.h>
#include <proto/chooser.h>
#include <proto/cia.h>
#include <proto/clicktab.h>
#include <proto/colorwheel.h>
#include <proto/commodities.h>
#include <proto/console.h>
#include <proto/datatypes.h>
#include <proto/datebrowser.h>
#include <proto/disk.h>
#include <proto/diskfont.h>
#include <proto/dos.h>
#include <proto/drawlist.h>
#include <proto/exec.h>
#include <proto/expansion.h>
#include <proto/fuelgauge.h>
#include <proto/gadtools.h>
#include <proto/getcolor.h>
#include <proto/getfile.h>
#include <proto/getfont.h>
#include <proto/getscreenmode.h>
#include <proto/glyph.h>
#include <proto/graphics.h>
#include <proto/icon.h>
#include <proto/iffparse.h>
#include <proto/input.h>
#include <proto/integer.h>
#include <proto/intuition.h>
#include <proto/keymap.h>
#include <proto/label.h>
#include <proto/layers.h>
#include <proto/layout.h>
#include <proto/listbrowser.h>
#include <proto/listview.h>
#include <proto/locale.h>
#include <proto/lowlevel.h>
#include <proto/mathieeedoubbas.h>
#include <proto/mathieeedoubtrans.h>
#include <proto/mathieeesingbas.h>
#include <proto/mathieeesingtrans.h>
#include <proto/misc.h>
#include <proto/nonvolatile.h>
#include <proto/palette.h>
#include <proto/penmap.h>
#include <proto/potgo.h>
#include <proto/radiobutton.h>
#include <proto/ramdrive.h>
#include <proto/realtime.h>
#include <proto/requester.h>
#include <proto/rexxsyslib.h>
#include <proto/scroller.h>
#include <proto/sketchboard.h>
#include <proto/slider.h>
#include <proto/space.h>
#include <proto/speedbar.h>
#include <proto/string.h>
#include <proto/texteditor.h>
#include <proto/timer.h>
#include <proto/trackfile.h>
#include <proto/translator.h>
#include <proto/utility.h>
#include <proto/virtual.h>
#include <proto/wb.h>
#include <proto/window.h>

#endif /* !PROTO_ALL_H */
